# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountUp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountUp
  pod 'Firebase/Core'

  target 'CountUpTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
  end

end
